import { MS_PER_DAY, MS_PER_MINUTE, TIME } from "@/lib/time";

export const LIMITS = {
  SLUG_MIN: 3,
  SLUG_MAX: 32,
  NAME_MAX: 80,
  NOTE_MAX: 500,
  PASSWORD_MIN: 8,
  PASSWORD_MAX: 128,
  BCRYPT_ROUNDS: 12,
  NANOID_SLUG: 7,
  NANOID_INVITE: 32,
  VISITOR_KEY_HEX: 32,
  INVITE_TTL_DAYS: 7,
  UNLOCK_COOKIE_DAYS: 30,
  UNFURL_TTL_DAYS: 7,
  UNFURL_MAX_KIB: 512,
  UNFURL_DIM_MAX: 50,
  UNFURL_TOKEN_MAX: 100,
  FILE_MAX_MIB: 15,
  BYTES_PER_KIB: 1024,
  STATS_TREND_DAYS: 14,
  STATS_RECENT_CLICKS: 50,
  QUERY_STALE_MINUTES: 5,
  QUERY_GC_MINUTES: 30,
  QUERY_PERSIST_DEBOUNCE_MS: 250,
  COPY_FEEDBACK_MS: 1500,
  BLOB_MULTIPART_MIN_BYTES: 4_000_000,
  ISO_DATE_LENGTH: 10,
} as const;

export const BYTES_PER_MIB = LIMITS.BYTES_PER_KIB * LIMITS.BYTES_PER_KIB;
export const MAX_FILE_BYTES = LIMITS.FILE_MAX_MIB * BYTES_PER_MIB;
export const MAX_UNFURL_BYTES = LIMITS.UNFURL_MAX_KIB * LIMITS.BYTES_PER_KIB;
export const INVITE_TTL_MS = LIMITS.INVITE_TTL_DAYS * MS_PER_DAY;
export const UNFURL_TTL_MS = LIMITS.UNFURL_TTL_DAYS * MS_PER_DAY;
export const QUERY_STALE_TIME_MS = LIMITS.QUERY_STALE_MINUTES * MS_PER_MINUTE;
export const QUERY_GC_TIME_MS = LIMITS.QUERY_GC_MINUTES * MS_PER_MINUTE;
export const UNLOCK_COOKIE_MAX_AGE_SECONDS =
  LIMITS.UNLOCK_COOKIE_DAYS * TIME.HOURS_PER_DAY * TIME.MINUTES_PER_HOUR * TIME.SECONDS_PER_MINUTE;
