export const TIME = {
  MS_PER_SECOND: 1000,
  SECONDS_PER_MINUTE: 60,
  MINUTES_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
} as const;

export const MS_PER_MINUTE = TIME.SECONDS_PER_MINUTE * TIME.MS_PER_SECOND;
export const MS_PER_HOUR = TIME.MINUTES_PER_HOUR * MS_PER_MINUTE;
export const MS_PER_DAY = TIME.HOURS_PER_DAY * MS_PER_HOUR;
